# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_auto_20180430_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='user',
        ),
    ]
